name: my_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dash==2.9.2
  - pandas==2.0.2
  - plotly==5.14.1
  - dash-bootstrap-components==1.4.1
  - numpy
  - gunicorn==20.1.0
  - faiss==1.7.4
  - sentence-transformers==2.2.2
  - pytables==3.8.0
  - openpyxl
  - flask-limiter==3.5.0
  - bleach