from dash import dcc, html, dash_table
import dash_bootstrap_components as dbc
#from layout.initial_radar_chart import initial_radar


columns = [
        {'name': 'ID', 'id': 'ID', 'hideable': False},
        {'name': 'Incident name', 'id': 'name', 'hideable': True},
        {"name": 'Description', 'id': "description", 'hideable': True},
        {'name': 'Start date', 'id': 'start_date', 'hideable': True},
        {"name": 'Incident type', 'id': "incident_type", 'hideable': True},
        {"name": 'Receiver name', 'id': "receiver_name", 'hideable': False},
        {"name": 'Receiver country', 'id': "receiver_country", 'hideable': True},
        {"name": 'Receiver category', 'id': "receiver_category", 'hideable': True},
        {"name": 'Initiator name', 'id': "initiator_name", 'hideable': False},
        {"name": 'Country of origin of initiator(s)', 'id': "initiator_country", 'hideable': True},
        {"name": 'Initiator category', 'id': "initiator_category", 'hideable': True},
        {"name": 'Number of attributions', 'id': "number_of_attributions", 'hideable': True},
        {"name": 'Attribution date', 'id': "attribution_date", 'hideable': True},
        {"name": 'Attribution type', 'id': "attribution_type", 'hideable': True},
        {"name": 'Attribution basis', 'id': "attribution_basis", 'hideable': True},
        {"name": 'Attributing country', 'id': "attributing_country", 'hideable': True},
        {"name": 'Number of political responses', 'id': "number_of_political_responses", 'hideable': True},
        {"name": 'Political response date', 'id': "political_response_date", 'hideable': True},
        {"name": 'Political response type', 'id': "political_response_type", 'hideable': True},
        {"name": 'Political response country', 'id': "political_response_country", 'hideable': True},
        {"name": 'Zero days', 'id': "zero_days", 'hideable': True},
        {"name": 'MITRE initial access', 'id': "MITRE_initial_access", 'hideable': True},
        {"name": 'MITRE impact', 'id': "MITRE_impact", 'hideable': True},
        {"name": 'Cyber intensity', 'id': "weighted_cyber_intensity", 'hideable': True},
        {"name": 'Impact indicator', 'id': "impact_indicator", 'hideable': True},
        {"name": 'State responsibility indicator', 'id': "state_responsibility_indicator", 'hideable': True},
        {"name": 'IL breach indicator', 'id': "IL_breach_indicator", 'hideable': True},
        {"name": 'Number of legal responses', 'id': "number_of_legal_responses", 'hideable': True},
        {"name": 'Legal response date', 'id': "legal_response_date", 'hideable': True},
        {"name": 'Legal response type', 'id': "legal_response_type", 'hideable': True},
        {"name": 'Legal response country', 'id': "legal_response_country", 'hideable': True},
        {'name': 'radar_score_impact', 'id': 'radar_score_impact', 'hideable': False},
        {'name': 'radar_score_intensity', 'id': 'radar_score_intensity', 'hideable': False},
        {'name': 'radar_score_political', 'id': 'radar_score_political', 'hideable': False},
        {'name': 'radar_score_legal', 'id': 'radar_score_legal', 'hideable': False},
        {'name': 'radar_score_offline_conflict', 'id': 'radar_score_offline_conflict', 'hideable': False},
        {'name': 'radar_score_attribution', 'id': 'radar_score_attribution', 'hideable': False},
    ]


# Define initial display columns in the DataTable
initial_columns = ['name', "description", 'start_date', 'receiver_country', 'incident_type', 'initiator_country']

# Define the DataTable initially with no data, the data is then generated by the callback function
datatable = dash_table.DataTable(
    id='datatable',
    data=[],
    columns=columns,
    sort_action="custom",
    sort_mode="single",
    sort_by=[],
    page_action="custom",
    page_current=0,
    page_size=20,
    style_cell={
        'whiteSpace': 'nowrap',
        'overflow': 'hidden',
        'textOverflow': 'ellipsis',
        'maxWidth': 0
    },
    tooltip_data=[],
    tooltip_duration=None,
    row_selectable='single',
    hidden_columns=[col["id"] for col in columns if col["id"] not in initial_columns],
    style_header={
        'backgroundColor': 'rgba(0, 44, 56, 0.1)',
        'fontWeight': 'bold',
        'color': 'rgb(0, 44, 56)',
        'fontFamily': 'sans-serif',
    },
    style_data={'border': '1px solid #dee2e6',
                'padding': '5px',
                'fontFamily': 'sans-serif',
                },
    css=[
        {'selector': '.dash-spreadsheet-menu', 'rule': 'padding: 5px'},
        {'selector': '.show-hide',
         'rule': 'font-family: Lato; font-size: 0.75rem; color: rgb(0, 44, 56); background-color: #dee2e6; border-radius: 5px; padding: 5px 5px; border: none;'},
    ]
)

body = dbc.Col(
    children=[
        dbc.Row([
                dbc.Col([
                    html.Div([
                        html.I(
                            className="fa-solid fa-table-list",
                            style={
                                'font-size': '1.5rem',
                                "display": "inline-block",
                                "margin-right": "10px",
                                'color': '#CC0130'
                            }
                        ),
                        html.H3("Database", style={'display': 'inline-block'}),
                        html.I(id='row-count',
                               style={'display': 'inline-block', 'margin-left': '10px', 'font-size': '1rem',
                                      'font-weight': 'bold'}),
                    ], style={'margin-bottom': '8px'}),
                ], style={'padding': '0px 10px', 'margin-top': '10px'}, width = 12),
        ], id="database-title", style={'margin-top': '0px', 'margin-bottom': '20px'}),
        dbc.Row([
            dbc.Col([
                dbc.Spinner([datatable]),
            ]),
        ], id="datatable-row", style={'margin-top': '0px', 'margin-bottom': '20px', "height": "500px"}),
        dbc.Row([
            dbc.Col([
                html.Div([
                    dbc.Button('Download filtered data', id='download-button', className="mb-3", color="primary",),
                    dcc.Download(id="download-dataframe-csv"),
                ], style={"text-align": "right"}),
            ], id="download_div", style={'margin-bottom': '55px'}, width=12),
        ], id="download_row"),
        dbc.Row([
            dbc.Col([
                dbc.Row([
                    dbc.Col([
                        html.Div([
                            html.H3([
                                html.I(
                                    className="fa-solid fa-magnifying-glass",
                                    style={
                                        'font-size': '1.5rem',
                                        "display": "inline-block",
                                        "margin-right": "10px",
                                        'color': '#CC0130'
                                    }
                                ),
                                html.Span("Incident details:", style={'display': 'inline-block', 'margin-right': '10px'}),
                                html.Span(id='datatable_info', style={'font-style': 'italic'})
                            ]),
                        ], style={'margin-bottom': '35px'}),
                    ])
                ]),
                dbc.Row([
                    dbc.Col([
                        dbc.Row([
                            html.Div([ html.I(
                                    className="fa-solid fa-share",
                                    style={
                                        'font-size': '1rem',
                                        "display": "inline-block",
                                        "margin-right": "5px",
                                        'color': '#CC0130'
                                    }
                                ), html.I(id='datatable_url', style={'display': 'inline-block', 'margin-right': '10px'})]),
                            html.Div(html.H4("Information coded in the database", style={'font-size': '1.3rem'})),
                        ], style={'margin-bottom': '20px'}),
                        dbc.Row([
                            html.Div(id="general_info_incident"),
                        ])
                    ], xs=12, sm=12, md=12, lg=6, xl=6, xxl=6, style={'padding-right': '25px', 'padding-left': '25px', 'margin-top': '20px'}),
                    dbc.Col([
                        dbc.Row([
                            html.Div(html.H4("Incident assessment", style={'font-size': '1.3rem'}))
                        ], style={'margin-bottom': '20px'}),
                        dbc.Row([
                            html.H6("Incident radar chart", style={'margin-top': '15px', 'font-size': '1.1rem', 'text-align': 'center'}),
                            html.P("This radar chart displays how the selected incident compares to the average scores of \
                            all incidents in the database across multiple indicators. \
                            Scores have been scaled from 0-4 for better comparability"),
                            html.Div([
                                dcc.Graph(
                                    id='incident_radar',
                                    #figure=initial_radar,
                                    config={
                                        "displayModeBar": False,
                                        #"scrollZoom": False,
                                        #'responsive': True
                                    }
                                ),
                            ], style={'margin-top': '20px', 'margin-bottom': '25px'}),
                            html.Div([
                                #dbc.Card([
                                    #dbc.CardBody([
                                        dbc.Row([
                                            dbc.Button([
                                                html.Span([
                                                    html.I(className="fa-solid fa-circle-info",
                                                           style={'font-size': '20px', 'color': '#CC0130'}),
                                                    html.B("Indicators explained", style={
                                                        'font-size': '1rem',
                                                        'margin-left': '10px',
                                                        'margin-right': '10px'
                                                    }),
                                                    html.I(className="fa fa-angle-down",
                                                           style={'font-size': '15px', 'color': '#002C38'})
                                                ], style={'text-align': 'center'})
                                            ],
                                            id="radar-collapse",
                                            className="mb-3",
                                            color="link",
                                            style={
                                                'color': 'rgb(0, 44, 56)',
                                                'text-align': 'center',
                                                'padding-bottom': '15px',
                                            },
                                            n_clicks=0,
                                        ),
                                dbc.Collapse([
                                                html.Ul([
                                                    html.Li([
                                                        html.B("Offline conflict intensity: "),
                                                        html.Span("This indicator applies to cyber incidents which are related \
                                                        to an offline conflict. The offline intensity scores are based on the "),
                                                           html.A("HIIK conflict database", href="https://hiik.de/?lang=en", target="_blank"),
                                                        "."
                                                    ]),
                                                    html.Li([
                                                        html.B("Cyber intensity: "),
                                                        html.Span("This indicator assesses each cyber incident, \
                                                        based on its physical effects and socio-political severity. \
                                                        Scores range from 1-15, however, for this specific \
                                                        radar chart, they are scaled down to a range of 0-4. This is designed \
                                                        to offer a more nuanced comparison of the selected incident \
                                                        against the backdrop of other incidents. For more information on the \
                                                        cyber intensity indicator, see our "),
                                                            html.A("methodology page", href="https://eurepoc.eu/methodology/", target="_blank"),
                                                    ]),
                                                    html.Li([
                                                        html.B("Impact indicator: "),
                                                        html.Span("This indicator measures the overall economic, political, \
                                                        intelligence and functional impact of a cyber incident. For more \
                                                        information on the methodology see our "),
                                                            html.A("codebook.", href="https://eurepoc.eu/wp-content/uploads/2023/07/EuRepoC_Codebook_1_2.pdf", target="_blank"),
                                                    ]),
                                                    html.Li([
                                                        html.B("Number of political/legal responses: "),
                                                        "Note that the radar chart does not indicate the absolute number of responses, \
                                                         but uses a score to reflect how the incident fares in comparison to \
                                                         other incidents in terms of the number of responses"
                                                    ]),
                                                    html.Li([
                                                        html.B("Attribution time: "),
                                                        html.Span("This indicator measures the number of days between the start \
                                                        of an incident and its first public attribution. As above, \
                                                        the score in the chart does not indicate the absolute number of days but \
                                                        reflects how the incident fares in comparison to other incidents"),
                                                    ]),
                                                ], style={'margin-left': '10px', 'margin-right': '10px', 'margin-top': '10px'}),
                                            ],
                                    id="collapse-radar-text",
                                    is_open=False
                                ),
                                        ]),
                                    #]),
                                #]),
                            ], style={'margin-bottom': '20px'}),
                        ], style={'border': "1px solid #e6eaeb", 'border-radius': '5px'}),
                    ], xs=12, sm=12, md=12, lg=6, xl=6, xxl=6, style={
                        'margin-top': '25px',
                        'padding-left': '25px',
                        'padding-right': '25px',
                    }),
                ])
            ]),
        ]),
    ],
    width=12,
    md={"size": 12},
    lg={"size": 12},
)
